(cl:in-package zzz_driver_msgs-msg)
(cl:export '(S-VAL
          S
          D-VAL
          D
          B-VAL
          B
          PSI_S-VAL
          PSI_S
          PSI_D-VAL
          PSI_D
          PSI_B-VAL
          PSI_B
          POSE_COVARIANCE-VAL
          POSE_COVARIANCE
          VS-VAL
          VS
          VD-VAL
          VD
          VB-VAL
          VB
          OMEGA_S-VAL
          OMEGA_S
          OMEGA_D-VAL
          OMEGA_D
          OMEGA_B-VAL
          OMEGA_B
          TWIST_COVARIANCE-VAL
          TWIST_COVARIANCE
          SA-VAL
          SA
          AD-VAL
          AD
          AB-VAL
          AB
          EPSILON_S-VAL
          EPSILON_S
          EPSILON_D-VAL
          EPSILON_D
          EPSILON_B-VAL
          EPSILON_B
          ACCEL_COVARIANCE-VAL
          ACCEL_COVARIANCE
))