Header header

#novatel long header
LongHeader long_header

  uint32 gps_week
# seconds of week
  float64 gps_seconds  
# All the measurements are in the SPAN computational frame: right, forward,up.
# change in angle around x axis in radians
  float64 x_angle_change     
# change in angle around y axis in radians
  float64 y_angle_change   
# change in angle around z axis in radians  
  float64 z_angle_change     
# change in velocity along x axis in m/s 
  float64 x_velocity_change  
# change in velocity along y axis in m/s
  float64 y_velocity_change  
# change in velocity along z axis in m/s
  float64 z_velocity_change 