(cl:in-package zzz_cognition_msgs-msg)
(cl:export '(UID-VAL
          UID
          CONFIDENCE-VAL
          CONFIDENCE
          CLS-VAL
          CLS
          STATE-VAL
          STATE
          FFSTATE-VAL
          FFSTATE
          LANE_INDEX-VAL
          LANE_INDEX
          LANE_ANGLEDIFF-VAL
          LANE_ANGLEDIFF
          LANE_DIST_LEFT_T-VAL
          LANE_DIST_LEFT_T
          LANE_DIST_RIGHT_T-VAL
          LANE_DIST_RIGHT_T
          LANE_DIST_S-VAL
          LANE_DIST_S
          IS_STATIC-VAL
          IS_STATIC
          SHAPE_TYPE-VAL
          SHAPE_TYPE
          SHAPE-VAL
          SHAPE
          DIMENSION-VAL
          DIMENSION
          SHAPE_UNCERTAINTY-VAL
          SHAPE_UNCERTAINTY
          BEHAVIOR-VAL
          BEHAVIOR
          PRIORITY-VAL
          PRIORITY
))