(cl:defpackage zzz_cognition_msgs-msg
  (:use )
  (:export
   "<DRIVINGSPACE>"
   "DRIVINGSPACE"
   "<DYNAMICBOUNDARY>"
   "DYNAMICBOUNDARY"
   "<DYNAMICBOUNDARYPOINT>"
   "DYNAMICBOUNDARYPOINT"
   "<JUNCTIONMAPSTATE>"
   "JUNCTIONMAPSTATE"
   "<LANESTATE>"
   "LANESTATE"
   "<MAPSTATE>"
   "MAPSTATE"
   "<MULTILANEMAPSTATE>"
   "MULTILANEMAPSTATE"
   "<ROADOBSTACLE>"
   "ROADOBSTACLE"
   "<VEHICLELOCATION>"
   "VEHICLELOCATION"
   "<VEHICLELOCATIONARRAY>"
   "VEHICLELOCATIONARRAY"
  ))

