(cl:in-package zzz_planning_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TRAJECTORY-VAL
          TRAJECTORY
          DESIRED_SPEED-VAL
          DESIRED_SPEED
          DESIRED_ACC-VAL
          DESIRED_ACC
          RLS_ACTION-VAL
          RLS_ACTION
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          THETA-VAL
          THETA
          KAPPA-VAL
          KAPPA
          S-VAL
          S
          DKAPPA-VAL
          DKAPPA
          DDKAPPA-VAL
          DDKAPPA
          V-VAL
          V
          A-VAL
          A
          RELATIVE_TIME-VAL
          RELATIVE_TIME
))