// Generated by gencpp from file zzz_perception_msgs/LaneDetectionArray.msg
// DO NOT EDIT!


#ifndef ZZZ_PERCEPTION_MSGS_MESSAGE_LANEDETECTIONARRAY_H
#define ZZZ_PERCEPTION_MSGS_MESSAGE_LANEDETECTIONARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <zzz_perception_msgs/LaneDetection.h>

namespace zzz_perception_msgs
{
template <class ContainerAllocator>
struct LaneDetectionArray_
{
  typedef LaneDetectionArray_<ContainerAllocator> Type;

  LaneDetectionArray_()
    : header()
    , detections()  {
    }
  LaneDetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::zzz_perception_msgs::LaneDetection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::zzz_perception_msgs::LaneDetection_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct LaneDetectionArray_

typedef ::zzz_perception_msgs::LaneDetectionArray_<std::allocator<void> > LaneDetectionArray;

typedef boost::shared_ptr< ::zzz_perception_msgs::LaneDetectionArray > LaneDetectionArrayPtr;
typedef boost::shared_ptr< ::zzz_perception_msgs::LaneDetectionArray const> LaneDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator1> & lhs, const ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator1> & lhs, const ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zzz_perception_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d293a0f68718e32c10240d4d4f142934";
  }

  static const char* value(const ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd293a0f68718e32cULL;
  static const uint64_t static_value2 = 0x10240d4d4f142934ULL;
};

template<class ContainerAllocator>
struct DataType< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zzz_perception_msgs/LaneDetectionArray";
  }

  static const char* value(const ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes lane detection list\n"
"\n"
"Header header\n"
"\n"
"LaneDetection[] detections\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: zzz_perception_msgs/LaneDetection\n"
"# Geometric representation of center line of the lane\n"
"float32[] center_line_coeffs\n"
"\n"
"# The location at the end of the line\n"
"float32 end_location\n"
;
  }

  static const char* value(const ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zzz_perception_msgs::LaneDetectionArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::zzz_perception_msgs::LaneDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZZZ_PERCEPTION_MSGS_MESSAGE_LANEDETECTIONARRAY_H
