# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from zzz_driver_msgs/ChassisReport.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ChassisReport(genpy.Message):
  _md5sum = "b0a29ac7eeffeb332f52a08cd1c9e8d0"
  _type = "zzz_driver_msgs/ChassisReport"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Information reported by chassis components

# Vehicle speed
float32 speed

# Wheel speed (rad/s)
int32 wheel_speed_fl
int32 wheel_speed_fr
int32 wheel_speed_rl
int32 wheel_speed_rr
"""
  __slots__ = ['speed','wheel_speed_fl','wheel_speed_fr','wheel_speed_rl','wheel_speed_rr']
  _slot_types = ['float32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       speed,wheel_speed_fl,wheel_speed_fr,wheel_speed_rl,wheel_speed_rr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ChassisReport, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.speed is None:
        self.speed = 0.
      if self.wheel_speed_fl is None:
        self.wheel_speed_fl = 0
      if self.wheel_speed_fr is None:
        self.wheel_speed_fr = 0
      if self.wheel_speed_rl is None:
        self.wheel_speed_rl = 0
      if self.wheel_speed_rr is None:
        self.wheel_speed_rr = 0
    else:
      self.speed = 0.
      self.wheel_speed_fl = 0
      self.wheel_speed_fr = 0
      self.wheel_speed_rl = 0
      self.wheel_speed_rr = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_f4i().pack(_x.speed, _x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.speed, _x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr,) = _get_struct_f4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_f4i().pack(_x.speed, _x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.speed, _x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr,) = _get_struct_f4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f4i = None
def _get_struct_f4i():
    global _struct_f4i
    if _struct_f4i is None:
        _struct_f4i = struct.Struct("<f4i")
    return _struct_f4i
