// Generated by gencpp from file zzz_cognition_msgs/DynamicBoundary.msg
// DO NOT EDIT!


#ifndef ZZZ_COGNITION_MSGS_MESSAGE_DYNAMICBOUNDARY_H
#define ZZZ_COGNITION_MSGS_MESSAGE_DYNAMICBOUNDARY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <zzz_cognition_msgs/DynamicBoundaryPoint.h>

namespace zzz_cognition_msgs
{
template <class ContainerAllocator>
struct DynamicBoundary_
{
  typedef DynamicBoundary_<ContainerAllocator> Type;

  DynamicBoundary_()
    : header()
    , boundary()  {
    }
  DynamicBoundary_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , boundary(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::zzz_cognition_msgs::DynamicBoundaryPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::zzz_cognition_msgs::DynamicBoundaryPoint_<ContainerAllocator> >::other >  _boundary_type;
  _boundary_type boundary;





  typedef boost::shared_ptr< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicBoundary_

typedef ::zzz_cognition_msgs::DynamicBoundary_<std::allocator<void> > DynamicBoundary;

typedef boost::shared_ptr< ::zzz_cognition_msgs::DynamicBoundary > DynamicBoundaryPtr;
typedef boost::shared_ptr< ::zzz_cognition_msgs::DynamicBoundary const> DynamicBoundaryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator1> & lhs, const ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.boundary == rhs.boundary;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator1> & lhs, const ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zzz_cognition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73db63c598006d00c116b478d56b2cc3";
  }

  static const char* value(const ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73db63c598006d00ULL;
  static const uint64_t static_value2 = 0xc116b478d56b2cc3ULL;
};

template<class ContainerAllocator>
struct DataType< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zzz_cognition_msgs/DynamicBoundary";
  }

  static const char* value(const ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message represents a compact dynamc environment representation with dynamic boundary\n"
"\n"
"Header header\n"
"DynamicBoundaryPoint[] boundary\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: zzz_cognition_msgs/DynamicBoundaryPoint\n"
"# This message represents a point in the dynamic boundary\n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 vx\n"
"float32 vy\n"
;
  }

  static const char* value(const ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.boundary);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicBoundary_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zzz_cognition_msgs::DynamicBoundary_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "boundary[]" << std::endl;
    for (size_t i = 0; i < v.boundary.size(); ++i)
    {
      s << indent << "  boundary[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::zzz_cognition_msgs::DynamicBoundaryPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.boundary[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZZZ_COGNITION_MSGS_MESSAGE_DYNAMICBOUNDARY_H
