// Generated by gencpp from file zzz_cognition_msgs/VehicleLocationArray.msg
// DO NOT EDIT!


#ifndef ZZZ_COGNITION_MSGS_MESSAGE_VEHICLELOCATIONARRAY_H
#define ZZZ_COGNITION_MSGS_MESSAGE_VEHICLELOCATIONARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <zzz_cognition_msgs/VehicleLocation.h>

namespace zzz_cognition_msgs
{
template <class ContainerAllocator>
struct VehicleLocationArray_
{
  typedef VehicleLocationArray_<ContainerAllocator> Type;

  VehicleLocationArray_()
    : header()
    , vehiclelocationarray()  {
    }
  VehicleLocationArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehiclelocationarray(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::zzz_cognition_msgs::VehicleLocation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::zzz_cognition_msgs::VehicleLocation_<ContainerAllocator> >::other >  _vehiclelocationarray_type;
  _vehiclelocationarray_type vehiclelocationarray;





  typedef boost::shared_ptr< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleLocationArray_

typedef ::zzz_cognition_msgs::VehicleLocationArray_<std::allocator<void> > VehicleLocationArray;

typedef boost::shared_ptr< ::zzz_cognition_msgs::VehicleLocationArray > VehicleLocationArrayPtr;
typedef boost::shared_ptr< ::zzz_cognition_msgs::VehicleLocationArray const> VehicleLocationArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator1> & lhs, const ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vehiclelocationarray == rhs.vehiclelocationarray;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator1> & lhs, const ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zzz_cognition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05a1add39e990f1618c38da9e9721a1b";
  }

  static const char* value(const ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05a1add39e990f16ULL;
  static const uint64_t static_value2 = 0x18c38da9e9721a1bULL;
};

template<class ContainerAllocator>
struct DataType< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zzz_cognition_msgs/VehicleLocationArray";
  }

  static const char* value(const ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"VehicleLocation[] vehiclelocationarray\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: zzz_cognition_msgs/VehicleLocation\n"
"Header header\n"
"\n"
"float64 lat\n"
"float64 lon\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehiclelocationarray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleLocationArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zzz_cognition_msgs::VehicleLocationArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehiclelocationarray[]" << std::endl;
    for (size_t i = 0; i < v.vehiclelocationarray.size(); ++i)
    {
      s << indent << "  vehiclelocationarray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::zzz_cognition_msgs::VehicleLocation_<ContainerAllocator> >::stream(s, indent + "    ", v.vehiclelocationarray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZZZ_COGNITION_MSGS_MESSAGE_VEHICLELOCATIONARRAY_H
